<?php
$this->layout(
	'system::layout/default',
	[
		'title'      => __('Login'),
		'page_title' => __('Login'),
	]
) ?>

<form method="post">
    <h4><?= __('Authorization') ?></h4>
	<?php
	if (!empty($error)): ?>
		<?= $this->fetch('system::app/alert', ['alert_type' => 'alert-danger', 'alert' => $error]) ?>
	<?php
	endif ?>
    <div class="form-group">
        <label for="login"><?= __('Username') ?></label>
        <input type="text"
               class="form-control"
               maxlength="20"
               name="n"
               id="login"
               required
               value="<?= $this->e($user_login) ?>"
               placeholder="<?= __('Username') ?>"
        >
    </div>
    <div class="form-group">
        <label for="password"><?= __('Password') ?></label>
        <input
                type="password"
                class="form-control"
                name="p"
                maxlength="20"
                id="password"
                required
                placeholder="<?= __('Password') ?>"
        >
    </div>
    <button type="submit" name="login" value="1" class="btn btn-fill btn-primary"><?= __('Login') ?></button>
    <a href="/profile/skl.php?continue" class="btn btn-link"><?= __('Forgot password?') ?></a>
    <div class="mt-3">
        <script async src="https://telegram.org/js/telegram-widget.js?22" data-telegram-login="john_auth_bot" data-size="large" data-radius="4" data-onauth="onTelegramAuth(user)" data-request-access="write"></script>
        <script type="text/javascript">
            function removeAlert(alertDiv) {
                setTimeout(function () {
                    alertDiv.fadeOut(500, function () {
                        $(this).remove();
                    });
                }, 3000);
            }

            function onTelegramAuth(user) {
                $.ajax({
                    url        : '/login/telegram/',
                    type       : 'POST',
                    contentType: 'application/json',
                    data       : JSON.stringify(user),
                    beforeSend : function () {
                        $(".alert.alert-danger").remove();
                    },
                    success    : function (response) {
                        if (response.success) {
                            window.location.href = '/';
                        } else {
                            let alertDiv = $('<div class="alert alert-danger">' + response.error + '</div>');
                            $("h4").after(alertDiv);
                            removeAlert(alertDiv);
                        }
                    },
                    error      : function (xhr, status, error) {
                        let alertDiv = $('<div class="alert alert-danger">' + error + '</div>');
                        $("h4").after(alertDiv);
                        removeAlert(alertDiv);
                    }
                });
            }
        </script>
    </div>
    <div class="mt-3">
        <a href="/registration" class="mr-2"><?= __('Registration') ?></a>
    </div>
</form>
